#!/usr/bin/env bash
set -euo pipefail
export SHELLOPTS
HERE=$(dirname "${BASH_SOURCE[0]}")
source libbashuu

uu::command::set-description "Destroy cluster"
uu::command::set-scope cluster
uu::command::import-option option-my-xc-name
uu::command::main "$@"

source my-xc-destroy-implementation
