#!/usr/bin/env bash
set -euo pipefail
export SHELLOPTS
HERE=$(dirname "${BASH_SOURCE[0]}")
source libbashuu

uu::command::set-description "Make sure network and nodes match current requirements"
uu::command::set-scope cluster
uu::command::import-option option-my-xc-name
uu::command::import-option option-my-xc-nodes-count
uu::command::import-option option-my-xc-ssh-private-key-path
uu::command::require-implementation my-xc-shape-implementation
uu::command::main "$@"

source my-xc-shape-implementation
