#!/usr/bin/env bash
HERE=$(dirname "${BASH_SOURCE[0]}")
source libbashuu
source xc-lib

uu::command::set-description "Stop running node (do not remove disk image)"
uu::command::set-scope node
uu::command::import-option option-my-xc-name
uu::command::import-option option-my-xc-node-id
uu::command::require-implementation my-xc-node-stop-implementation
uu::command::main "$@"

source my-xc-node-stop-implementation
